### ISSUE TITLE
Access Denied (sorry your link has timed out)

### ISSUE THREAD

**Issue by FrancoisYu** [jobready/thunderzippy#3]
I've setup a EC server/GoLang/thunderzippy successfully. 
I use the following command to create the link:

curl -H "Content-Type: application/json" -X POST -d '[{"Filepath":"images/example.jpg","Url":"https://upload.wikimedia.org/wikipedia/mediawiki/a/a9/Example.jpg"}]' http://localhost:8080/zip/{"ref":"z95h07"}

But when I try to get the zip download file with the following command, I got  Access Denied
curl http://localhost:8080/zip/?ref=z95h07 -o "download.zip"

Is there anything wrong or any setting I should check.

**Comment by FrancoisYu** [comment]
Finally found the reason why.
I cannot pass the ref code while creating the zip, I can only wait the response and use the ticket no to reference the d/l link.

curl -H "Content-Type: application/json" -X POST -d '[{"Filepath":"images/example.jpg","Url":"https://upload.wikimedia.org/wikipedia/mediawiki/a/a9/Example.jpg"}]' http://localhost:8080/zip

**Comment by s01ipsist** [comment]
That's correct. The ref code is supplied in the response from the initial POST request and used in the subsequent GET request. I can see why the README might have mislead you on this through lack of whitespace and will look at clarifying the documentation. Thanks.
