### ISSUE TITLE
Is Redis is mendatory?

### ISSUE THREAD

**Issue by sukhjindersingh** [jobready/thunderzippy#5]
@chrism-jobready Firstly thanks for providing such a awesome script.

I came across to your API from [here](http://engineroom.teamwork.com/how-to-securely-provide-a-zip-download-of-a-s3-file-bundle/). Under that you have commented 

> Really liked this idea. We reworked it to be a simple RESTful API **without any shared redis instance**. We've open sourced our implementation at https://github.com/jobready/thunderzippy/issues/new

However when I used your script locally and disabled Redis I got the curl error 

> Error: failed with status 100, response , curl_error Empty reply from server, curl_errno 52

May be I am wrong, please elaborate more on whether for this API Redis is mendatory?

**Comment by s01ipsist** [comment]
The emphasis was on the "shared" nature of the Redis instance. Thunderzippy still uses Redis to store the file list, as you have observed.
