### ISSUE TITLE
Large set of data download causes Broken Pipe

### ISSUE THREAD

**Issue by sukhjindersingh** [jobready/thunderzippy#6]
We successfully integrated your script how sometime if user stops downloading or if there are large set of file 400+ files to download we are getting **write tcp 98.76.34.234:8080->123.456.789.12:52399: write: broken pipe**

Please advices, what could be the cause if it.

**Comment by s01ipsist** [comment]
I haven't seen this myself but we do not have the need to bundle more than 100 files at a time. 

Patches are welcome.
